id: A44858429
title: Prayer for the Long Life of His Holiness the Dalai Lama
type: translation
pechas:
- I4997944A
- IBF4B2A10
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:17.313081
  last_modified_at: 2023-01-04 11:48:17.313085
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I4997944A/56FB: B8E8
  IBF4B2A10/E89B: B8E8
